#!/bin/sh
#
#

if [ -e /etc/firefly_bridge/bridge_config ];then
    source /etc/firefly_bridge/bridge_config
else
    return 0
fi

if [ $ENABLE == "0" ];then
    return 0
fi

case "$1" in
    start)
        printf "Starting bridge: "
	brctl addbr br0
	brctl addif br0 eth0
	brctl addif br0 eth1
	ifconfig eth0  0.0.0.0
	ifconfig eth1  0.0.0.0
	ifconfig br0 192.168.2.1:24
	if ps -ef|grep -v grep|grep dhcpd ;then
		killall dhcpd
		sleep 1
	fi
	dhcpd -q
        ;;
    stop)
        printf "Stopping bridge: "
	brctl delif br0 eth0
	brctl delif br0 eth1
	ifconfig br0 down
	brctl delbr br0

	# restart dhcpcd
	if ps -ef|grep -v grep|grep dhcpcd ;then
		killall dhcpcd
		sleep 1
	fi
	dhcpcd -f /etc/dhcpcd.conf
        ;;
    restart|reload)
        "$0" stop
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit $?
